spring: 
  application: 
    name: zuul-eureka
server: 
  port: ${SERVER_PORT:80}
    
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    svcmesh:
      path: /svcmesh/**
      service-id: backend-service      

eureka:
  client: 
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: ${EUREKA_SERVERS}
      
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

     