spring: 
  application: 
    name: zuul-eureka
server: 
  port: ${SERVER_PORT:80}
    
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:      
    svcmesh:
      path: /svcmesh/**
      service-id: backend-statefulset
  retryable: true 
  
ribbon:  
  eureka:
    enabled: true                     # eureka에서 server list를 가져올지 여부 
  
svcmesh:
  ribbon:   
    MaxAutoRetries: 3                   # 동일 서비스 연결시도 횟수: 최소 1번 이상으로 지정
    MaxAutoRetiresNextServer: 2         # 다음 서비스 연결 시도 횟수: 대상 서비스 수 이상으로 지정
    OkToRetryOnAllOperations: true      # Retry 사용 여부: Failover하려면 true로 지정 
    ConnectTimeout: 3000
    ReadTimeout: 1000
    retryableStatusCodes: 503, 408, 500, 404
      
eureka:
  client: 
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: ${EUREKA_SERVERS}
      
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

     