spring: 
  application: 
    name: zuul-eureka
server: 
  port: ${SERVER_PORT:80}
    
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  ribbon: 
    eager-load:
      enabled: true 
  prefix: /svcmesh 
  #ignored-services: '*'
  
eureka:
  instance: 
    prefer-ip-address: true 
    hostname: backend-service
  client: 
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: ${EUREKA_SERVERS}
      
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

     